DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS genres_films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friends CASCADE;

CREATE TABLE IF NOT EXISTS mpa (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(40)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200),
    releaseDate date,
    duration integer,
    mpa int REFERENCES mpa
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40),
    login varchar(40) NOT NULL,
    name varchar(40),
    birthday date
);

CREATE TABLE IF NOT EXISTS likes (
    user_id int REFERENCES users,
    film_id int REFERENCES films,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS genres (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(40)
);

CREATE TABLE IF NOT EXISTS genres_films (
    genre_id int REFERENCES genres,
    film_id int REFERENCES films,
    PRIMARY KEY (genre_id, film_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id int REFERENCES users,
    user_friend_id int REFERENCES users,
    PRIMARY KEY (user_id, user_friend_id)
);

INSERT INTO genres (name)
VALUES ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'), ('Боевик');

INSERT INTO mpa (name)
VALUES ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');